services:
  app:
    container_name: kelvin_app
    depends_on:
      - db
      - redis
    profiles: [ prod ]
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    restart: unless-stopped
    environment:
      # Hardcode the DB and Redis hostnames and ports, since they necessarily
      # run inside the same Docker network, as they are defined in this docker-compose.yml file.
      - DATABASE__HOST=db
      - DATABASE__PORT=5432
      - REDIS__HOST=redis
      - REDIS__PORT=6379
    env_file:
      - .env
    volumes:
      - app_static:/app/static
      - app_socket:/socket
      - ${KELVIN__LOCAL_SETTINGS_PATH}:/app/kelvin/local_settings.py:ro
      - ${UWSGI__CONFIG_PATH}:/app/uwsgi.ini:ro

  db:
    container_name: kelvin_db
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DATABASE__DB}
      - POSTGRES_USER=${DATABASE__USERNAME}
      - POSTGRES_PASSWORD=${DATABASE__PASSWORD}
    env_file:
      - .env
    volumes:
      - ${DATABASE__DATA_PATH}:/var/lib/postgresql/data
    ports:
      - "${DATABASE__PORT}:5432"

  redis:
    container_name: kelvin_redis
    image: redis:7
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${REDIS__DATA_PATH}:/data
    ports:
      - "${REDIS__PORT}:6379"
    # Save Redis DB to disk at least once per 30 minutes
    # Set maximum DB size to 1 GiB, evict all old keys
    command: "redis-server --save 1800 1 300 100 60 1000 --maxmemory 1024mb --maxmemory-policy allkeys-lru --loglevel warning"

  nginx:
    image: nginx:1.26
    container_name: kelvin_nginx
    depends_on:
      - app
    restart: unless-stopped
    profiles: [ prod ]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX__CONFIG_PATH}:/etc/nginx/nginx.conf:ro
      - ${NGINX__CERTS_PATH}:/etc/nginx/certs:ro
      - ${NGINX__LOGS_PATH}:/var/log/nginx
      - app_static:/app/static:ro
      - app_socket:/socket

volumes:
  app_static:
  app_socket:
