# Generated by Django 4.2.16 on 2026-04-28 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0033_remove_email_sent_at_email_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('public_key', models.TextField(editable=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='common.class')),
            ],
            options={
                'verbose_name_plural': 'class sessions',
            },
        ),
        migrations.CreateModel(
            name='AttendanceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('method', models.CharField(choices=[('qr', 'QR Code'), ('ble', 'Bluetooth Low Energy')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_tokens', to='attendance.classsession')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this token', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_tokens', to=settings.AUTH_USER_MODEL)),
                ('created_by_device', models.ForeignKey(blank=True, help_text='Attendance device used to create this token', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_tokens', to='attendance.attendancedevice')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_time', models.DateTimeField(help_text="The time when the student's attendance was recorded")),
                ('is_present', models.BooleanField(default=True, help_text='Whether the student is marked as present in the class')),
                ('record_format', models.CharField(choices=[('automatic', 'Automatic (Device-based)'), ('manual_student', 'Manual (Student-initiated)'), ('manual_teacher', 'Manual (Teacher-initiated)')], help_text='How the attendance record was created', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional notes about this attendance record (e.g. why was the student marked as not present)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.classsession')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('created_by_device', models.ForeignKey(blank=True, help_text='Attendance device used to authorize creation of this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_records', to='attendance.attendancedevice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'attendance records',
                'ordering': ['class_session', 'student', 'attendance_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.CheckConstraint(check=models.Q(('end__gt', models.F('start'))), name='end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='attendancetoken',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__gt', models.F('created_at'))), name='expires_after_creation'),
        ),
        migrations.AddConstraint(
            model_name='attendancedevice',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('user',), name='unique_active_device_per_user'),
        ),
        migrations.AddConstraint(
            model_name='attendancedevice',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('user',), name='unique_pending_device_per_user'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_session', 'student', 'attendance_time'], name='attendance__class_s_276d82_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'attendance_time'], name='attendance__student_f5b6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_session', 'attendance_time'], name='attendance__class_s_ceeb19_idx'),
        ),
    ]
