# Generated by Django 4.2.16 on 2026-04-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsession',
            old_name='Class',
            new_name='clazz',
        ),
    ]
